app:
  title: DDD House 服务门户
  baseUrl: http://backstage.zouhang.com
  packages: all
  extensions:
    - page:catalog:
        config:
          path: /

organization:
  name: DDD House

backend:
  baseUrl: http://backstage.zouhang.com
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://backstage.zouhang.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection:
      directory: /data
  actions:
    pluginSources:
      - auth
      - catalog
      - scaffolder

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  endpoints:
    /prometheus:
      target: http://kps-kube-prometheus-stack-prometheus.monitoring:9090
      changeOrigin: true
    /alertmanager:
      target: http://kps-kube-prometheus-stack-alertmanager.monitoring:9093
      changeOrigin: true

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local

auth:
  providers:
    guest: {}

scaffolder: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ./catalog/ddd-house.yaml

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: local
          url: https://kubernetes.default.svc
          authProvider: serviceAccount
          skipTLSVerify: true

permission:
  enabled: false
